DB_HOST='127.0.0.1'
DB_PORT=5432
DB_NAME='demographer'
DB_USER='postgres'
DB_PASSWORD='root'
DB_TABLE_NAME='Student_residency'

COUNTRY_MAPPING = {
'Burkina Faso':'BFA',
'Mali':'MLI',
'Burundi':'BDI',
'Mexico':'MEX',
'Kenya':'KEN',
'Estonia':'EST',
'Moldova':'MDA',
'Qatar':'QAT',
'Hungary':'HUN',
'Namibia':'NAM',
'Latvia':'LVA',
'Brunei':'BRN',
'United Arab Emirates':'ARE',
'Belgium':'BEL',
'Congo (Brazzaville)':'COG',
'Mongolia':'MNG',
'Antarctica':'ATA',
'Gabon':'GAB',
'Cambodia':'KHM',
'Germany':'DEU',
'Puerto Rico':'PRI',
'Egypt':'EGY',
'Uruguay':'URY',
'Philippines':'PHL',
'French Southern and Antarctic Lands':'ATF',
'Nepal':'NPL',
'Trinidad and Tobago':'TTO',
'Poland':'POL',
'Netherlands':'NLD',
'France':'FRA',
'Kyrgyzstan':'KGZ',
'Greece':'GRC',
'Sri Lanka':'LKA',
'South Africa':'ZAF',
'Ecuador':'ECU',
'South Sudan, Republic of':'SSD',
'New Zealand':'NZL',
'West Bank':'PSE',
'Albania':'ALB',
'Bulgaria':'BGR',
'Sudan':'SDN',
'Russia':'RUS',
'Chile':'CHL',
'Suriname':'SUR',
'Serbia':'SRB',
'Morocco':'MAR',
'Cuba':'CUB',
'Finland':'FIN',
'Austria':'AUT',
'Myanmar':'MMR',
'Tunisia':'TUN',
'Peru':'PER',
'El Salvador':'SLV',
'Colombia':'COL',
'Japan':'JPN',
'Ireland':'IRL',
'Equatorial Guinea':'GNQ',
'Australia':'AUS',
'Guinea':'GIN',
'Senegal':'SEN',
'Oman':'OMN',
'Djibouti':'DJI',
'Libya':'LBY',
'United Kingdom':'GBR',
'Malaysia':'MYS',
'Guinea Bissau':'GNB',
'Sweden':'SWE',
'Ethiopia':'ETH',
'Haiti':'HTI',
'Angola':'AGO',
'Jordan':'JOR',
'Slovakia':'SVK',
'Bolivia':'BOL',
'Togo':'TGO',
'Pakistan':'PAK',
'Saudi Arabia':'SAU',
'China':'CHN',
'Mozambique':'MOZ',
'Iceland':'ISL',
'Laos':'LAO',
'Slovenia':'SVN',
'Malawi':'MWI',
'Guyana':'GUY',
'Uzbekistan':'UZB',
'Congo (Kinshasa)':'COD',
'Fiji':'FJI',
'Algeria':'DZA',
'Guatemala':'GTM',
'Bangladesh':'BGD',
'Dominican Republic':'DOM',
'Czech Republic':'CZE',
'Falkland Islands':'FLK',
'Swaziland':'SWZ',
'Brazil':'BRA',
'Bosnia and Herzegovina':'BIH',
'Paraguay':'PRY',
'Costa Rica':'CRI',
'Uganda':'UGA',
'Kazakhstan':'KAZ',
'Bahamas, The':'BHS',
'Argentina':'ARG',
'East Timor':'TLS',
'Syria':'SYR',
'Italy':'ITA',
'Gambia':'GMB',
'Belarus':'BLR',
'Honduras':'HND',
'Cote d\'Ivoire':'CIV',
'Azerbaijan':'AZE',
'Lesotho':'LSO',
'Benin':'BEN',
'Eritrea':'ERI',
'North Korea':'PRK',
'Venezuela':'VEN',
'New Caledonia':'NCL',
'Botswana':'BWA',
'Norway':'NOR',
'Lebanon':'LBN',
'Nigeria':'NGA',
'Nicaragua':'NIC',
'Madagascar':'MDG',
'Cyprus':'CYP',
'Armenia':'ARM',
'Iraq':'IRQ',
'Ghana':'GHA',
'Cameroon':'CMR',
'Bhutan':'BTN',
'Zambia':'ZMB',
'Central African Republic':'CAF',
'Canada':'CAN',
'Switzerland':'CHE',
'Vietnam':'VNM',
'Israel':'ISR',
'Indonesia':'IDN',
'Sierra Leone':'SLE',
'South Korea':'KOR',
'Panama':'PAN',
'Solomon Islands':'SLB',
'Liberia':'LBR',
'Somalia':'SOM',
'Macedonia':'MKD',
'Ukraine':'UKR',
'Romania':'ROU',
'Montenegro':'MNE',
'French Guiana':'GUF',
'Greenland':'GRL',
'India':'IND',
'Rwanda':'RWA',
'Zimbabwe':'ZWE',
'Portugal':'PRT',
'Denmark':'DNK',
'Vanuatu':'VUT',
'Western Sahara':'ESH',
'Chad':'TCD',
'Jamaica':'JAM',
'Luxembourg':'LUX',
'Lithuania':'LTU',
'Turkey':'TUR',
'Spain':'ESP',
'Kuwait':'KWT',
'Mauritania':'MRT',
'United States of America':'USA',
'Iran':'IRN',
'United Republic of Tanzania':'TZA',
'Taiwan':'TWN',
'Papua New Guinea':'PNG',
'Croatia':'HRV',
'Tajikistan':'TJK',
'Turkmenistan':'TKM',
'Belize':'BLZ',
'Thailand':'THA',
'Georgia':'GEO',
'Afghanistan':'AFG',
'Niger':'NER',
'Yemen':'YEM',
'Somaliland':'-99',
# Additional Country
'Unknown Nation':'UNKW',
'Malta':'MALT',
'Singapore':'SING',
'St Lucia':'STLU',
'Tanzania':'TANZ',
'Hong Kong':'HNKG',
'Barbados':'BARB',
'Former Yugoslavia':'FRYU',
'Anguilla':'ANGU',
'Grenada':'GREN',
'Monaco':'MONA',
'Bahrain':'BAHR',
'Kosovo':'KOSO',
'Mauritius':'MAUR',
'Macau':'MACA',
'Christmas Island':'CHIS',
'Papau New Guinea':'PAPA'
}

STATE_MAPPING = {    
'Iowa':'IA',
'Indiana':'IN',
'New Jersey':'NJ',
'Texas':'TX',
'District of Columbia':'DC',
'Kentucky':'KY',
'Hawaii':'HI',
'Minnesota':'MN',
'Idaho':'ID',
'Nevada':'NV',
'Georgia':'GA',
'Tennessee':'TN',
'Arkansas':'AR',
'Kansas':'KS',
'Virginia':'VA',
'Maine':'ME',
'Massachusetts':'MA',
'California':'CA',
'Rhode Island':'RI',
'Alabama':'AL',
'New Mexico':'NM',
'Ohio':'OH',
'Oklahoma':'OK',
'Wyoming':'WY',
'Vermont':'VT',
'West Virginia':'WV',
'Illinois':'IL',
'Nebraska':'NE',
'New Hampshire':'NH',
'North Dakota':'ND',
'Connecticut':'CT',
'Pennsylvania':'PA',
'Maryland':'MD',
'Wisconsin':'WI',
'New York':'NY',
'Louisiana':'LA',
'Delaware':'DE',
'Colorado':'CO',
'South Dakota':'SD',
'Michigan':'MI',
'Missouri':'MO',
'Mississippi':'MS',
'Utah':'UT',
'Alaska':'AK',
'Florida':'FL',
'South Carolina':'SC',
'Arizona':'AZ',
'North Carolina':'NC',
'Washington':'WA',
'Montana':'MT',
'Oregon':'OR',
# Additional States
'Unknown State':'UN',
'Canal Zone':'CZ',
'Guam':'GU',
'Puerto Rico':'PR',
'Virgin Islands':'VI'
}

COUNTY_MAPPING = {
'Augusta':'VA21',
'Clarke':'VA25',
'Williamsburg':'VA23',
'Wythe':'VA107',
'Tazewell':'VA37',
'Prince William':'VA97',
'Bedford Co.':'VA104',
'Pittsylvania':'VA39',
'Cumberland':'VA124',
'Warren':'VA50',
'Craig':'VA53',
'Prince George':'VA90',
'Fairfax Co.':'VA11',
'Amherst':'VA15',
'Gloucester':'VA101',
'Greensville':'VA98',
'Bath':'VA20',
'York':'VA34',
'Alexandria':'VA38',
'Goochland':'VA103',
'Charlottesville':'VA2',
'Winchester':'VA134',
'Charles City':'VA77',
'Norfolk':'VA110',
'Brunswick':'VA58',
'Roanoke':'VA4',
'Northumberland':'VA70',
'Fairfax City':'VA133',
'Fluvanna':'VA67',
'James City':'VA84',
'Page':'VA69',
'Floyd':'VA92',
'Bristol':'VA72',
'Nelson':'VA73',
'Powhatan':'VA129',
'Richmond Co.':'VA108',
'Dickenson':'VA91',
'Manassas Park':'VA59',
'Shenandoah':'VA14',
'Surry':'VA43',
'King William':'VA78',
'Sussex':'VA57',
'Petersburg':'VA125',
'Suffolk':'VA49',
'Orange':'VA28',
'Harrisonburg':'VA54',
'Wise':'VA76',
'Lee':'VA3',
'Henry':'VA95',
'Westmoreland':'VA26',
'Northampton':'VA111',
'Culpeper':'VA31',
'Prince Edward':'VA47',
'Highland':'VA9',
'Richmond':'VA75',
'Staunton':'VA100',
'Chesapeake':'VA112',
'Radford':'VA87',
'Lunenburg':'VA56',
'Virginia Beach':'VA105',
'Falls Church':'VA81',
'Lynchburg':'VA29',
'Emporia':'VA35',
'Giles':'VA119',
'King George':'VA8',
'Halifax':'VA19',
'Lexington':'VA45',
'Loudoun':'VA85',
'Bedford':'VA24',
'Buena Vista':'VA114',
'Martinsville':'VA71',
'Patrick':'VA113',
'Greene':'VA126',
'Essex':'VA66',
'Middlesex':'VA48',
'New Kent':'VA117',
'Madison':'VA5',
'Salem':'VA127',
'Rockingham':'VA122',
'Covington':'VA88',
'Arlington':'VA89',
'Washington':'VA86',
'Hopewell':'VA44',
'Appomattox':'VA131',
'Rockbridge':'VA36',
'Hampton':'VA41',
'Rappahannock':'VA10',
'Frederick':'VA46',
'Accomack':'VA121',
'Hanover':'VA96',
'Dinwiddie':'VA12',
'Chesterfield':'VA99',
'Franklin Co.':'VA64',
'Colonial Heights':'VA120',
'Waynesboro':'VA93',
'Spotsylvania':'VA42',
'Fauquier':'VA63',
'Amelia':'VA102',
'Manassas':'VA132',
'Newport News':'VA33',
'Campbell':'VA94',
'Henrico':'VA109',
'Smyth':'VA55',
'Scott':'VA65',
'Caroline':'VA115',
'Mathews':'VA123',
'King & Queen':'VA68',
'Fredericksburg':'VA83',
'Mecklenburg':'VA27',
'Buchanan':'VA22',
'Grayson':'VA16',
'Pulaski':'VA40',
'Louisa':'VA80',
'Franklin':'VA30',
'Alleghany':'VA32',
'Galax':'VA128',
'Charlotte':'VA116',
'Montgomery':'VA82',
'Stafford':'VA51',
'Norton':'VA79',
'Albemarle':'VA18',
'Botetourt':'VA17',
'Southampton':'VA13',
'Russell':'VA52',
'Roanoke Co.':'VA106',
'Poquoson':'VA118',
'Bland':'VA61',
'Nottoway':'VA1',
'Lancaster':'VA6',
'Portsmouth':'VA74',
'Buckingham':'VA7',
'Isle of Wight':'VA62',
'Carroll':'VA60',
'Danville':'VA130',
# Additional County
'Clifton Forge':'CLFO',
'Unknown County':'UNKW',
'VA Unknown':'VAUN'
}